### ISSUE TITLE
Fix platform registry and add test to test with NERC

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/ocean-data-parser#88]
MEDS pointed out that some platforms where not appropriately associated with the right code. It would be great to fix those issues and potentially prevent them in the future. 

# TODO 

- [ ] Update `Capt Jacques Cartier` platform to ICES CODE: 18QL
- [ ] Update `John Cabot` platform to ICES CODE: 18KF
- [ ] Add tests to platform code list for each ICES assigned platforms:
   - [ ] Test NERC C17 match
   - [ ] Test attributes matches for each mapped ICES platforms.
